nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["http://127.0.0.1"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["^http://localhost:[0-9]+$", "^http://127.0.0.1:[0-9]+$", "^http://127.0.0.1:5173"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS", "PATCH"]
      max_age: 3600
